[package]
name                   = "once-fn"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
description            = "cache the result of a function so its body runs only once"
readme                 = "../README.md"
repository.workspace   = true
license.workspace      = true
keywords               = ["cache", "once", "proc-macro"]
categories             = ["rust-patterns"]

[dependencies]
once-fn-macros = { workspace = true }

[dev-dependencies]
tokio    = { version = "1.53", features = ["full"] }
trybuild = "1.0.119"

[lints]
workspace = true
