[package]
name                   = "once-fn-macros"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
description            = "procedural macros for the once-fn crate"
repository.workspace   = true
license.workspace      = true
keywords               = ["cache", "once", "proc-macro"]
categories             = ["rust-patterns"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote       = "1.0"
syn         = { version = "3.0", features = ["full"] }

[dev-dependencies]
once-fn = { path = "../once-fn" }

[lints]
workspace = true
