name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v7
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall -y --no-symlinks cargo-nextest
      - name: Setup sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.11
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo nextest run --workspace && cargo test --doc --workspace
      - run: cargo clippy --workspace --all-targets -- -D warnings
      - run: cargo fmt --all --check
